// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as StylesColors$TestPresentationApp from "./StylesColors.bs.js";

function buttonStyles(buttonType) {
  return CssJs.style([
              CssJs.backgroundColor(buttonType === "delete" ? CssJs.hex(StylesColors$TestPresentationApp.colors.red.main) : CssJs.hex(StylesColors$TestPresentationApp.colors.green.main)),
              CssJs.padding(CssJs.px(20)),
              CssJs.cursor(CssJs.pointer),
              CssJs.color(CssJs.white),
              CssJs.fontSize(CssJs.px(16)),
              CssJs.borderStyle(CssJs.none),
              CssJs.borderRadius(CssJs.px(4)),
              CssJs.hover([
                    CssJs.backgroundColor(buttonType === "delete" ? CssJs.hex(StylesColors$TestPresentationApp.colors.red.dark) : CssJs.hex(StylesColors$TestPresentationApp.colors.green.dark)),
                    CssJs.transitionDuration(300)
                  ])
            ]);
}

function todoContainerStyles(param) {
  return CssJs.style([
              CssJs.display("flex"),
              CssJs.alignItems(CssJs.center)
            ]);
}

function todoTextStyles(param) {
  return CssJs.style([CssJs.marginRight(CssJs.px(20))]);
}

export {
  buttonStyles ,
  todoContainerStyles ,
  todoTextStyles ,
  
}
/* CssJs Not a pure module */
