// Generated by ReScript, PLEASE EDIT WITH CARE


var colors = {
  red: {
    main: "f44336",
    dark: "d32f2f"
  },
  green: {
    main: "4caf50",
    dark: "388e3c"
  }
};

export {
  colors ,
  
}
/* No side effect */
