// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Styles$TestPresentationApp from "./Styles.bs.js";

function Todo(Props) {
  var handleRemoveTodo = Props.handleRemoveTodo;
  var id = Props.id;
  var text = Props.text;
  var handleEditTodo = Props.handleEditTodo;
  var match = React.useState(function () {
        return "";
      });
  var setNewTodoText = match[1];
  var newTodoText = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setIsEditing = match$1[1];
  var isEditing = match$1[0];
  return React.createElement("div", {
              className: Styles$TestPresentationApp.todoContainerStyles(undefined)
            }, isEditing ? React.createElement("input", {
                    defaultValue: text,
                    className: Styles$TestPresentationApp.todoTextStyles(undefined),
                    onChange: (function (e) {
                        return Curry._1(setNewTodoText, e.target.value);
                      })
                  }) : React.createElement("div", {
                    className: Styles$TestPresentationApp.todoTextStyles(undefined)
                  }, text), React.createElement("button", {
                  className: Styles$TestPresentationApp.buttonStyles("delete"),
                  onClick: (function (param) {
                      return Curry._1(handleRemoveTodo, id);
                    })
                }, "X"), isEditing ? React.createElement("button", {
                    className: Styles$TestPresentationApp.buttonStyles("add"),
                    onClick: (function (param) {
                        Curry._1(handleEditTodo, {
                              text: newTodoText,
                              id: id
                            });
                        return Curry._1(setIsEditing, (function (param) {
                                      return false;
                                    }));
                      })
                  }, "save") : React.createElement("button", {
                    className: Styles$TestPresentationApp.buttonStyles("add"),
                    onClick: (function (param) {
                        return Curry._1(setIsEditing, (function (param) {
                                      return true;
                                    }));
                      })
                  }, "edit"));
}

var make = Todo;

export {
  make ,
  
}
/* react Not a pure module */
